spring:
  cloud:
    # cn.baiqi.gateway 网关
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      default-filters:
        - name: IpRequestRateLimiter
          args:
            key-resolver: "#{@ipKeyResolver}"
            redis-rate-limiter.replenishRate: 10 #字段为令牌桶恢复速度，即每秒访问个数
            redis-rate-limiter.burstCapacity: 40 #字段为令牌桶大小，即峰值流量来临时最大可访问数
      routes:
        - id: ap-user
          uri: http://127.0.0.1:9021/
          predicates:
            - Path=/ap-user/**
          filters:
            # 1表示过滤一个路径
            - StripPrefix=1
        - id: ap-admire
          uri: http://127.0.0.1:9022/
          predicates:
            - Path=/ap-admire/**
          filters:
            # 1表示过滤一个路径
            - StripPrefix=1



# 忽略 url 拦截
ap.global-filter:
  ignoreUrlSet:
    - /user/login
    - /user/register
    - /commodity/page
    - /ld-druid/
    - /test
    - /ali-callback
  authorization: Authorization