ld:
  host: ENC(1fHqntDo2ht9xE0zoq9FN77qsdKNS1UjUBLYkKgfPlDlTQFptbqqbdOsTnfvMonB)
  mysql-port: 3306
  nacos-port: ENC(sXRB5Z4DD4W8LjplEYGE/R6THAD3Yee7A9C5umRpaiOToCZznqN0iBjrHpw/ARlU)
  redis-port: ENC(f2tcahincqmqsxEffvNLCVJJRdv6A3Ek1bft3M6jsW6X1geh/p19UEavLQQvvouk)
  druid-password: ENC(s4pqk4zcbnCXVkHToIb7qpprPpTCugQI7bQ6uYTGgvpWNt9YT/8ZsTYeZZZMIGCL)
  druid-url-mapper: "/ap-druid/*"
#  mq-host1: ENC(3BCpEOcT+EQydXwv3rGAABquKt4CgGP3J7+FU9FmRp9/m5N/raQmNQYzuiA7N5T8)
#  mq-port1: ENC(ci0eGG90xENVUh5GQyelub0dQaDkJqNg19k/2LARa6J/icVgzo4s0atqag0xWDyl)
#  mq-host2: ENC(mUF8TbTk79WcSyG05+eoIrqUSGvQgWFGnKXMO8g2u/XkKumOK4tht2rEc9bzzqCM)
#  mq-port2: ENC(d6wkpbfJrJfmkVQD7uFoMIKCvtzC8gtA+RDhcl0Yb2k+rxzgk4L+fBC+fU5AU33J)
#nacos
nacos:
  #dev
  namespace: edf88515-a6a4-4e64-86f5-0a92ffd74e01
#database
DB_HOST: ${ld.host}:${ld.mysql-port}
# dev
DB_NAME: admire-platform
DB_USERNAME: root
DB_PASSWORD: ENC(s4pqk4zcbnCXVkHToIb7qpprPpTCugQI7bQ6uYTGgvpWNt9YT/8ZsTYeZZZMIGCL)
REDIS_PASSWORD: ENC(s4pqk4zcbnCXVkHToIb7qpprPpTCugQI7bQ6uYTGgvpWNt9YT/8ZsTYeZZZMIGCL)


MQ_NAME_SERVER: ${ld.mq-host1}:${ld.mq-port1};${ld.mq-host2}:${ld.mq-port2}
MQ_GROUP: admire_platform